services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-Postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dreamly
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  meilidata: